[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/oferta-especial"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/oferta-especial/"
  to = "/index.html"
  status = 200
